services:

  image-match:
    build:
      context: .
    image: ascribe/image-match
    container_name: image-match
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/.venv
    depends_on:
     - "elasticsearch"
     - "mongodb"
     - "opensearch"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.5.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - http.host=0.0.0.0
      - cluster.name=docker-cluster
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"

  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.name=opensearch-docker
    ports:
      - "9201:9200"

  bdocs:
    build:
      context: .
    image: ascribe/image-match
    container_name: bdocs
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/.venv
    working_dir: /usr/src/app/docs
    command: uv run --all-extras make html

  vdocs:
    image: nginx:alpine
    ports:
      - '40080:80'
    volumes:
      - ./docs/build/html:/usr/share/nginx/html
